project_id = "xhfqjupiidexvlltstal"

[functions.create-sale-user]
verify_jwt = false

[functions.create-staff-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.export-crm-to-google-sheets]
verify_jwt = false

[functions.send-gcal-invite]
verify_jwt = false

[functions.sync-company-event-to-google]
verify_jwt = false

[functions.cancel-company-event]
verify_jwt = false

[functions.send-template-test-invite]
verify_jwt = false

[functions.ai-sales-assistant]
verify_jwt = false

[functions.embed-product-knowledge]
verify_jwt = false