/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as ReportsCrmRouteImport } from './routes/reports/crm'
import { Route as OrdersNewRouteImport } from './routes/orders/new'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as MarketingReportsRouteImport } from './routes/marketing/reports'
import { Route as MarketingCampaignsRouteImport } from './routes/marketing/campaigns'
import { Route as CustomersIdRouteImport } from './routes/customers/$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTemplatesRouteImport } from './routes/admin/templates'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const ReportsCrmRoute = ReportsCrmRouteImport.update({
  id: '/reports/crm',
  path: '/reports/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingReportsRoute = MarketingReportsRouteImport.update({
  id: '/marketing/reports',
  path: '/marketing/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingCampaignsRoute = MarketingCampaignsRouteImport.update({
  id: '/marketing/campaigns',
  path: '/marketing/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/customers/$id': typeof CustomersIdRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/reports': typeof MarketingReportsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/reports/crm': typeof ReportsCrmRoute
  '/customers/': typeof CustomersIndexRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/customers/$id': typeof CustomersIdRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/reports': typeof MarketingReportsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/reports/crm': typeof ReportsCrmRoute
  '/customers': typeof CustomersIndexRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/customers/$id': typeof CustomersIdRoute
  '/marketing/campaigns': typeof MarketingCampaignsRoute
  '/marketing/reports': typeof MarketingReportsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/reports/crm': typeof ReportsCrmRoute
  '/customers/': typeof CustomersIndexRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/customers'
    | '/login'
    | '/profile'
    | '/signup'
    | '/admin/templates'
    | '/admin/users'
    | '/customers/$id'
    | '/marketing/campaigns'
    | '/marketing/reports'
    | '/orders/$id'
    | '/orders/new'
    | '/reports/crm'
    | '/customers/'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/login'
    | '/profile'
    | '/signup'
    | '/admin/templates'
    | '/admin/users'
    | '/customers/$id'
    | '/marketing/campaigns'
    | '/marketing/reports'
    | '/orders/$id'
    | '/orders/new'
    | '/reports/crm'
    | '/customers'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/customers'
    | '/login'
    | '/profile'
    | '/signup'
    | '/admin/templates'
    | '/admin/users'
    | '/customers/$id'
    | '/marketing/campaigns'
    | '/marketing/reports'
    | '/orders/$id'
    | '/orders/new'
    | '/reports/crm'
    | '/customers/'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  MarketingCampaignsRoute: typeof MarketingCampaignsRoute
  MarketingReportsRoute: typeof MarketingReportsRoute
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  ReportsCrmRoute: typeof ReportsCrmRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/reports/crm': {
      id: '/reports/crm'
      path: '/reports/crm'
      fullPath: '/reports/crm'
      preLoaderRoute: typeof ReportsCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/reports': {
      id: '/marketing/reports'
      path: '/marketing/reports'
      fullPath: '/marketing/reports'
      preLoaderRoute: typeof MarketingReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/campaigns': {
      id: '/marketing/campaigns'
      path: '/marketing/campaigns'
      fullPath: '/marketing/campaigns'
      preLoaderRoute: typeof MarketingCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CustomersRoute: CustomersRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  MarketingCampaignsRoute: MarketingCampaignsRoute,
  MarketingReportsRoute: MarketingReportsRoute,
  OrdersIdRoute: OrdersIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  ReportsCrmRoute: ReportsCrmRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
